name: Publish Package
on:
  workflow_dispatch: {}
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '**.md'
      - '**.png'
      - '**.json'
    branches: [master]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Package job

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        id: setup-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        id: login-ghcr
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # dockerServer Token
        continue-on-error: true
      - 
        id: login-dockerhub
        name: login to qdtoday DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QD_DOCKER_USERNAME }} # dockerServer Username 在setting创建secrets name=QD_DOCKER_USERNAME  value=dockerid
          password: ${{ secrets.QD_DOCKER_PASSWORD }} # dockerServer Token 在setting创建secrets name=QD_DOCKER_PASSWORD  value=dockerToken
        continue-on-error: true
      - 
        id: login-a76yyyy
        name: Login to a76yyyy DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # dockerServer Username 在setting创建secrets name=DOCKER_USERNAME  value=dockerid
          password: ${{ secrets.DOCKER_PASSWORD }} # dockerServer Token 在setting创建secrets name=DOCKER_PASSWORD  value=dockerToken
        continue-on-error: true
      -
        id: meta
        name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository_owner }}/qd,enable=${{ steps.login-ghcr.outcome == 'success'}}
            name=docker.io/undo8785/qd,enable=${{ steps.login-dockerhub.outcome == 'success'}}
            name=docker.io/acooler15/qiandao,enable=${{ steps.login-a76yyyy.outcome == 'success'}}
          tags: |
            type=ref,event=tag
            type=raw,value=dev
      - 
        name: Publish Latest Package
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7 # 你准备构建的镜像平台
          push: true
          tags: ${{ steps.meta.outputs.tags }}